all: run

run: aa
	@chmod 000 aa; ls -l aa
	@chmod 001 aa; ls -l aa
	@chmod 011 aa; ls -l aa
	@chmod 111 aa; ls -l aa
	@chmod 1111 aa; ls -l aa
	@chmod 2111 aa; ls -l aa
	@chmod 4111 aa; ls -l aa
	@chmod 7111 aa; ls -l aa
	rm -f aa

clean:
	rm -f aa
