all: run

run:
	@echo ">>>>>>  This step takes about 1.5hrs."
	# ./configure-buildroot.sh raspberrypi3 2>&1 | tee rpi3_configure.log
	./configure-buildroot.sh raspberrypi4 2>&1 | tee rpi4_configure.log

clean:
